### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by adeluna84** [phpcfdi/sat-catalogos#7]
$ composer require phpcfdi/satcatalogos

  [InvalidArgumentException]
  Could not find a matching version of package phpcfdi/satcatalogos. Check the package spelling, your version constra
  int and that the package is available in a stability which matches your minimum-stability (dev).

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by eclipxe13** [comment]
The project was in an early development process.
The development is continued.
Before first public release, you can use `composer require phpcfdi/sat-catalogos:master-dev`
