### ISSUE TITLE
Obtener todos los registros por catálogo

### ISSUE THREAD

**Issue by rafaelcr** [phpcfdi/sat-catalogos#8]
Estoy intentando usar este repo para construir los seeds de un nuevo proyecto, sin embargo, ahorita esta librería sólo me permite hacer queries por `id` en cada catálogo.

Lo que yo necesito es poder traerme todas las entradas de cualquier catálogo hacia un arreglo para entonces iterarlo y hacer los inserts a mi base de datos con mi propia estructura en cada uno de los registros.

Cómo puedo lograr esto? Hay forma de hacer un query que se traiga todo en lugar de filtrar por ID?

Gracias

**Comment by eclipxe13** [comment]
Creo que el proyecto que más te puede ayudar para la tarea es https://github.com/phpcfdi/resources-sat-catalogs que contiene un dump de base de datos (formato sqlite3) con todos los inserts. Este proyecto se basa en ese repositorio, también parte de phpCfdi.

También te podrías conectar directamente a la base de datos (en lugar de usar la librería como intermediario) porque el propósito de lo que pretendes hacer es diferente al propósito de esta librería (exponer los catálogos como objetos).

Recuerda que tenemos un chat de la comunidad de phpCfdi en https://discord.gg/aFGYXvX donde igualmente podrías obtener ayuda y soporte.

**Comment by rafaelcr** [comment]
Perfecto, gracias por la ayuda

**Comment by julio101290** [comment]
> Estoy intentando usar este repo para construir los seeds de un nuevo proyecto, sin embargo, ahorita esta librería sólo me permite hacer queries por `id` en cada catálogo.
> 
> Lo que yo necesito es poder traerme todas las entradas de cualquier catálogo hacia un arreglo para entonces iterarlo y hacer los inserts a mi base de datos con mi propia estructura en cada uno de los registros.
> 
> Cómo puedo lograr esto? Hay forma de hacer un query que se traiga todo en lugar de filtrar por ID?
> 
> Gracias

Seria de esta forma ejemplo $usosCFDI = $satCatalogos->usosCfdi40()->searchByField("texto", "%%", 10000);
